import { FaArrowTrendUp } from "react-icons/fa6";
import { TbDotsVertical } from "react-icons/tb";
import { TbCurrencyNaira } from "react-icons/tb";
import { BiCalculator } from "react-icons/bi";
import { LuLeaf } from "react-icons/lu";

export const MonthlyRemittanceData = [
  {
    id: "1",
    lga: "SUV/Minibus",
    expectedAmount: "25,000",
    actualAmountPaid: "25,000",
    dueDate: "15-01-2024",
    status: "On Time",
    action: TbDotsVertical,

    totalRevColl: {
      title: "Total Revenue Collected",
      iconMain: LuLeaf,
      totalRevColl: "680,000,000",
      iconArrow: FaArrowTrendUp,
      value: "+12%",
      label: "vs last month",

      lastmonth: {
        icon: FaArrowTrendUp,
        iconColor: "#16a34a",
        // iconSize: 16,
        value: "+12%",
        label: "vs last month",
        valueColor: "success",
      },
    },

    totalRemSent: {
      title: "Total Remittance Sent",
      iconMain: BiCalculator,
      totalRemSent: "612,000,000",
      iconArrow: FaArrowTrendUp,
      value: "+7.5%",
      label: "vs last month",

      lastmonth: {
        icon: FaArrowTrendUp,
        iconColor: "#16a34a",
        // iconSize: 16,
        value: "+7.5%",
        label: "vs last month",
        valueColor: "success",
      },
    },
    remittanceRate: {
      title: "Remittance Rate",
      iconMain: TbCurrencyNaira,
      remittanceRate: "92%",
      iconArrow: FaArrowTrendUp,
      value: "+3.5%",
      label: "vs last month",

      lastmonth: {
        icon: FaArrowTrendUp,
        iconColor: "#16a34a",
        // iconSize: 16,
        value: "+3.5%",
        label: "vs last month",
        valueColor: "success",
      },
    },
  },
  {
    id: "2",
    lga: "Salon Car",
    expectedAmount: "30,000",
    actualAmountPaid: "30,000",
    dueDate: "16-01-2024",
    status: "On Time",
    action: TbDotsVertical,
  },
  {
    id: "3",
    lga: "Motorcycle",
    expectedAmount: "35,000",
    actualAmountPaid: "35,000",
    dueDate: "17-01-2024",
    status: "On Time",
    action: TbDotsVertical,
  },
  {
    id: "4",
    lga: "32-seater Bus",
    expectedAmount: "40,000",
    actualAmountPaid: "40,000",
    dueDate: "18-01-2024",
    status: "Overdue",
    action: TbDotsVertical,
  },
  {
    id: "5",
    lga: "Truck",
    expectedAmount: "45,000",
    actualAmountPaid: "45,000",
    dueDate: "19-01-2024",
    status: "On Time",
    action: TbDotsVertical,
  },
  {
    id: "6",
    lga: "Tricycle",
    expectedAmount: "50,000",
    actualAmountPaid: "50,000",
    dueDate: "20-01-2024",
    status: "Overdue",
    action: TbDotsVertical,
  },
  {
    id: "7",
    lga: "Van",
    expectedAmount: "55,000",
    actualAmountPaid: "55,000",
    dueDate: "21-01-2024",
    status: "On Time",
    action: TbDotsVertical,
  },
  {
    id: "8",
    lga: "Pickup Truck",
    expectedAmount: "60,000",
    actualAmountPaid: "60,000",
    dueDate: "22-01-2024",
    status: "On Time",
    action: TbDotsVertical,
  },
  {
    id: "9",
    lga: "Heavy Duty Truck",
    expectedAmount: "65,000",
    actualAmountPaid: "65,000",
    dueDate: "23-01-2024",
    status: "Overdue",
    action: TbDotsVertical,
  },
  {
    id: "10",
    lga: "18-seater Bus",
    expectedAmount: "70,000",
    actualAmountPaid: "70,000",
    dueDate: "24-01-2024",
    status: "Pending",
    action: TbDotsVertical,
  },
];
